# -*- coding: utf-8 -*-
"""核心領域邏輯：影像載入、指標計算、缺陷偵測、判定與流程串接。"""

from .analyzer import ImageAnalyzer
from .config import Thresholds
from .dataset_manifest import (
    AcceptanceDatasetManifest,
    ImageEvidence,
    ManifestError,
    PreconditionLock,
    SessionInput,
    SessionPartition,
    build_dataset_manifest,
    build_image_evidence,
    load_image_sidecar,
    partition_sessions,
    sha256_file,
    sidecar_candidates,
)
from .detector import DefectDetector, DefectResult, RoiCnrResult, roi_cnr
from .g1_measurement import (
    DefectPolarity,
    G1MeasurementInputs,
    G1MeasurementReport,
    G1Measurer,
    MissingG1EvidenceError,
)
from .g2_measurement import (
    G2MeasurementError,
    G2MeasurementInputs,
    G2MeasurementReport,
    G2Measurer,
    ScaleEvidence,
    SlantedEdgeEvidence,
)
from .g3_measurement import (
    G3MeasurementError,
    G3MeasurementInputs,
    G3MeasurementReport,
    G3Measurer,
    SensorFrameSeries,
)
from .g5_measurement import (
    AcquisitionIntegrityEvidence,
    G5MeasurementError,
    G5MeasurementInputs,
    G5MeasurementReport,
    G5Measurer,
    ImageContract,
    ImageObservation,
    InterCameraGrayEvidence,
    StitchEvidence,
)
from .image import MeasurementPlaneError, RawImage
from .judge import AcceptanceJudge
from .legacy_adapter import LegacyMetricsAdapter, legacy_metrics_to_measurements
from .metrics import Metrics
from .pipeline import AcceptancePipeline, AnalysisResult
from .roi import (
    RoiCollection,
    RoiCreationMethod,
    RoiDefinition,
    RoiError,
    RoiType,
    RoiValidationIssue,
    ZoneMeasurement,
    apply_fixed_rois,
    extract_rois,
    measure_16_zones,
    measure_raw_16_zones,
)
from .specification import (
    MetricSpecification,
    SpecificationError,
    V4Specification,
    load_default_v4_spec,
    load_v4_spec,
)
from .temporal_analysis import (
    RRObservation,
    TemperatureRecord,
    TemporalAcceptanceMeasurer,
    TemporalAnalysisError,
    TemporalMeasurementInputs,
    TemporalMeasurementReport,
    TemporalSeries,
)
from .traceability import TraceabilityReport, TraceabilityValidator
from .v4_domain import (
    AcceptanceManifest,
    AcceptanceSession,
    ImageLevel,
    MeasurementResult,
    MetricGroup,
    OpticalMode,
    OverallResult,
    Severity,
)
from .v4_judge import (
    S0PriorityEvent,
    S0PriorityEventType,
    V4AcceptanceJudge,
    V4Decision,
)

__all__ = [
    "ImageAnalyzer",
    "Thresholds",
    "AcceptanceDatasetManifest",
    "ImageEvidence",
    "ManifestError",
    "PreconditionLock",
    "SessionInput",
    "SessionPartition",
    "build_dataset_manifest",
    "build_image_evidence",
    "load_image_sidecar",
    "partition_sessions",
    "sha256_file",
    "sidecar_candidates",
    "DefectDetector",
    "DefectResult",
    "RoiCnrResult",
    "roi_cnr",
    "DefectPolarity",
    "G1MeasurementInputs",
    "G1MeasurementReport",
    "G1Measurer",
    "MissingG1EvidenceError",
    "G2MeasurementError",
    "G2MeasurementInputs",
    "G2MeasurementReport",
    "G2Measurer",
    "ScaleEvidence",
    "SlantedEdgeEvidence",
    "G3MeasurementError",
    "G3MeasurementInputs",
    "G3MeasurementReport",
    "G3Measurer",
    "SensorFrameSeries",
    "AcquisitionIntegrityEvidence",
    "G5MeasurementError",
    "G5MeasurementInputs",
    "G5MeasurementReport",
    "G5Measurer",
    "ImageContract",
    "ImageObservation",
    "InterCameraGrayEvidence",
    "StitchEvidence",
    "RawImage",
    "MeasurementPlaneError",
    "AcceptanceJudge",
    "LegacyMetricsAdapter",
    "legacy_metrics_to_measurements",
    "Metrics",
    "AcceptancePipeline",
    "AnalysisResult",
    "RoiCollection",
    "RoiCreationMethod",
    "RoiDefinition",
    "RoiError",
    "RoiType",
    "RoiValidationIssue",
    "ZoneMeasurement",
    "apply_fixed_rois",
    "extract_rois",
    "measure_16_zones",
    "measure_raw_16_zones",
    "MetricSpecification",
    "SpecificationError",
    "V4Specification",
    "load_default_v4_spec",
    "load_v4_spec",
    "RRObservation",
    "TemperatureRecord",
    "TemporalAcceptanceMeasurer",
    "TemporalAnalysisError",
    "TemporalMeasurementInputs",
    "TemporalMeasurementReport",
    "TemporalSeries",
    "TraceabilityReport",
    "TraceabilityValidator",
    "AcceptanceManifest",
    "AcceptanceSession",
    "ImageLevel",
    "MeasurementResult",
    "MetricGroup",
    "OpticalMode",
    "OverallResult",
    "Severity",
    "S0PriorityEvent",
    "S0PriorityEventType",
    "V4AcceptanceJudge",
    "V4Decision",
]
